# Generated by Django 3.2 on 2022-11-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221123_1056'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "content"."genre_film_work"
            ADD CONSTRAINT "genre_film_work_film_work_id_genre_id_uniq"
            UNIQUE ("film_work_id", "genre_id");
            """,
            reverse_sql='ALTER TABLE "content"."genre_film_work" DROP CONSTRAINT genre_film_work_film_work_id_genre_id_uniq',
        ),

        migrations.RunSQL(
            sql="""
            ALTER TABLE "content"."person_film_work"
            ADD CONSTRAINT "person_film_work_film_work_id_person_id_uniq"
            UNIQUE ("film_work_id", "person_id");
            """,
            reverse_sql='ALTER TABLE "content"."person_film_work" DROP CONSTRAINT person_film_work_film_work_id_person_id_uniq',
        ),
    ] 
    
    
